services:
    web:
        image: space-web:latest
        pull_policy: always
        environment:
            - NODE_ENV=production
        restart: unless-stopped
        networks:
            - proxy

networks:
    proxy:
        external: true
        name: ${PROXY_NETWORK:-proxy}
